service: hillbrook-traffic
app: hillbrook-traffic
org: kielni

provider:
  name: aws
  runtime: python3.7
  memorySize: 128
  timeout: 30
  region: us-west-2
  role: ${env:LAMBDA_ROLE_ARN}

  iamRoleStatements:
    - Effect: Allow
      Action:
       - logs:CreateLogGroup
       - logs:CreateLogStream
       - logs:PutLogEvents
      Resource: ${env:LOGS_ARN}
    - Effect: Allow
      Action:
        - Allow: sns:Publish
      Resource: ${env:ALERT_ARN}
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: ${env:PARAMS_ARN}

  environment:
    STATIONS: ${env:STATIONS}
    ALERT_ARN: ${env:ALERT_ARN}
    GOOGLE_SHEET_ID: ${env:GOOGLE_SHEET_ID}

package:
  exclude:
      - node_modules/**
      - init.sh

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
      # to make serverless work with pyenv
      pythonBin: python
      dockerizePip: true

functions:
  collect-sheet:
    handler: handler.collect_to_sheet
    name: hillbook-traffic-sheet
    description: Get traffic data from SNAPS and send to Google Sheet (managed through serverless)
    events:
      - schedule: cron(10,25,40,55 0-4,12-23 ? * * *)
